-- AutoTest v3 Schema — extends v2 with intent engine, coverage, flakiness, artifacts, environments

-- ========== ORIGINAL TABLES (preserved) ==========

CREATE TABLE IF NOT EXISTS targets (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  base_url TEXT NOT NULL,
  auth_type TEXT DEFAULT 'none',
  auth_config TEXT DEFAULT '{}',
  settings TEXT DEFAULT '{}',
  environment TEXT DEFAULT 'default',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS scans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target_id INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending',
  stats TEXT DEFAULT '{}',
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS discovered_pages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scan_id INTEGER NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  title TEXT,
  status_code INTEGER,
  response_time INTEGER,
  has_forms INTEGER DEFAULT 0,
  is_auth_page INTEGER DEFAULT 0,
  ui_elements TEXT DEFAULT '{}',
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS discovered_apis (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scan_id INTEGER NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
  method TEXT NOT NULL,
  url TEXT NOT NULL,
  response_status INTEGER,
  response_type TEXT,
  requires_auth INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS discovered_forms (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  scan_id INTEGER NOT NULL REFERENCES scans(id) ON DELETE CASCADE,
  page_url TEXT NOT NULL,
  action TEXT,
  method TEXT DEFAULT 'GET',
  fields TEXT DEFAULT '[]',
  is_login_form INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now'))
);

CREATE TABLE IF NOT EXISTS test_runs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target_id INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
  scan_id INTEGER REFERENCES scans(id),
  test_types TEXT DEFAULT '[]',
  ai_prompt TEXT,
  status TEXT DEFAULT 'pending',
  summary TEXT DEFAULT '{}',
  started_at TEXT,
  finished_at TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  -- v3 additions
  plan_id INTEGER REFERENCES test_plans(id),
  environment TEXT DEFAULT 'default',
  git_sha TEXT,
  git_branch TEXT,
  browser TEXT DEFAULT 'chromium',
  retry_policy TEXT DEFAULT '{"maxRetries":2,"backoff":"linear"}',
  artifacts_path TEXT
);

CREATE TABLE IF NOT EXISTS test_results (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  run_id INTEGER NOT NULL REFERENCES test_runs(id) ON DELETE CASCADE,
  category TEXT NOT NULL,
  test_name TEXT NOT NULL,
  status TEXT NOT NULL,
  duration INTEGER,
  error_message TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  -- v3 additions
  retry_count INTEGER DEFAULT 0,
  is_flaky INTEGER DEFAULT 0,
  is_quarantined INTEGER DEFAULT 0,
  severity TEXT DEFAULT 'normal',
  feature_area TEXT,
  screenshot_path TEXT,
  trace_path TEXT,
  video_path TEXT,
  console_logs TEXT,
  network_logs TEXT,
  steps_json TEXT,
  defect_summary TEXT
);

-- ========== NEW v3 TABLES ==========

-- Test plans generated by AI Intent Engine
CREATE TABLE IF NOT EXISTS test_plans (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target_id INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
  intent TEXT NOT NULL,
  objectives TEXT DEFAULT '[]',
  user_stories TEXT DEFAULT '[]',
  risk_map TEXT DEFAULT '{}',
  test_matrix TEXT DEFAULT '{}',
  acceptance_criteria TEXT DEFAULT '[]',
  coverage_map TEXT DEFAULT '{}',
  status TEXT DEFAULT 'draft',
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Individual test cases within a plan
CREATE TABLE IF NOT EXISTS test_plan_cases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plan_id INTEGER NOT NULL REFERENCES test_plans(id) ON DELETE CASCADE,
  objective_id TEXT,
  name TEXT NOT NULL,
  description TEXT,
  category TEXT DEFAULT 'functional',
  priority TEXT DEFAULT 'medium',
  test_type TEXT DEFAULT 'happy_path',
  steps_json TEXT DEFAULT '[]',
  preconditions TEXT,
  expected_result TEXT,
  tags TEXT DEFAULT '[]',
  role TEXT DEFAULT 'user',
  created_at TEXT DEFAULT (datetime('now'))
);

-- Flakiness tracking
CREATE TABLE IF NOT EXISTS flaky_tests (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  test_name TEXT NOT NULL,
  category TEXT NOT NULL,
  target_id INTEGER REFERENCES targets(id) ON DELETE CASCADE,
  total_runs INTEGER DEFAULT 0,
  total_failures INTEGER DEFAULT 0,
  total_retries INTEGER DEFAULT 0,
  flake_rate REAL DEFAULT 0.0,
  is_quarantined INTEGER DEFAULT 0,
  quarantined_at TEXT,
  last_failure_at TEXT,
  last_error TEXT,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now')),
  UNIQUE(test_name, category, target_id)
);

-- Artifacts stored per test result
CREATE TABLE IF NOT EXISTS artifacts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  result_id INTEGER REFERENCES test_results(id) ON DELETE CASCADE,
  run_id INTEGER NOT NULL REFERENCES test_runs(id) ON DELETE CASCADE,
  type TEXT NOT NULL,
  name TEXT NOT NULL,
  path TEXT NOT NULL,
  size_bytes INTEGER DEFAULT 0,
  mime_type TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Environment configurations
CREATE TABLE IF NOT EXISTS environments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  base_url TEXT,
  variables TEXT DEFAULT '{}',
  accounts TEXT DEFAULT '{}',
  is_default INTEGER DEFAULT 0,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Auth sessions for reuse (Strategy A: storage state)
CREATE TABLE IF NOT EXISTS auth_sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target_id INTEGER NOT NULL REFERENCES targets(id) ON DELETE CASCADE,
  auth_type TEXT NOT NULL,
  storage_state TEXT NOT NULL,
  cookies TEXT DEFAULT '[]',
  expires_at TEXT,
  is_valid INTEGER DEFAULT 1,
  created_at TEXT DEFAULT (datetime('now')),
  updated_at TEXT DEFAULT (datetime('now'))
);

-- Coverage tracking
CREATE TABLE IF NOT EXISTS coverage_entries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  plan_id INTEGER REFERENCES test_plans(id) ON DELETE CASCADE,
  run_id INTEGER REFERENCES test_runs(id) ON DELETE CASCADE,
  objective TEXT NOT NULL,
  test_case TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  covered_at TEXT,
  created_at TEXT DEFAULT (datetime('now'))
);

-- Insert default environment
INSERT OR IGNORE INTO environments (name, is_default) VALUES ('default', 1);
